language: generic
sudo: false
git:
  depth: 10

matrix:
  include:
    - os: linux
      env: VIM_VERSION=v7.4
    - os: linux
      env: VIM_VERSION=v8.0.0000
    - os: linux
      env: VIM_VERSION=master

addons:
  apt:
    packages:
      - language-pack-ja
      - vim

install:
  - bash scripts/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - test/run.sh
  - make force_compile check
